// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.4
// source: entity.proto

package main

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EntityServiceClient is the client API for EntityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EntityServiceClient interface {
	GetEntityWithPagination(ctx context.Context, in *EntityRequest, opts ...grpc.CallOption) (*EntityResponse, error)
	GetEntityWithStream(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (EntityService_GetEntityWithStreamClient, error)
}

type entityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEntityServiceClient(cc grpc.ClientConnInterface) EntityServiceClient {
	return &entityServiceClient{cc}
}

func (c *entityServiceClient) GetEntityWithPagination(ctx context.Context, in *EntityRequest, opts ...grpc.CallOption) (*EntityResponse, error) {
	out := new(EntityResponse)
	err := c.cc.Invoke(ctx, "/main.EntityService/GetEntityWithPagination", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entityServiceClient) GetEntityWithStream(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (EntityService_GetEntityWithStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &EntityService_ServiceDesc.Streams[0], "/main.EntityService/GetEntityWithStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &entityServiceGetEntityWithStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type EntityService_GetEntityWithStreamClient interface {
	Recv() (*Entity, error)
	grpc.ClientStream
}

type entityServiceGetEntityWithStreamClient struct {
	grpc.ClientStream
}

func (x *entityServiceGetEntityWithStreamClient) Recv() (*Entity, error) {
	m := new(Entity)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// EntityServiceServer is the server API for EntityService service.
// All implementations must embed UnimplementedEntityServiceServer
// for forward compatibility
type EntityServiceServer interface {
	GetEntityWithPagination(context.Context, *EntityRequest) (*EntityResponse, error)
	GetEntityWithStream(*emptypb.Empty, EntityService_GetEntityWithStreamServer) error
	mustEmbedUnimplementedEntityServiceServer()
}

// UnimplementedEntityServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEntityServiceServer struct {
}

func (UnimplementedEntityServiceServer) GetEntityWithPagination(context.Context, *EntityRequest) (*EntityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEntityWithPagination not implemented")
}
func (UnimplementedEntityServiceServer) GetEntityWithStream(*emptypb.Empty, EntityService_GetEntityWithStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method GetEntityWithStream not implemented")
}
func (UnimplementedEntityServiceServer) mustEmbedUnimplementedEntityServiceServer() {}

// UnsafeEntityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EntityServiceServer will
// result in compilation errors.
type UnsafeEntityServiceServer interface {
	mustEmbedUnimplementedEntityServiceServer()
}

func RegisterEntityServiceServer(s grpc.ServiceRegistrar, srv EntityServiceServer) {
	s.RegisterService(&EntityService_ServiceDesc, srv)
}

func _EntityService_GetEntityWithPagination_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntityServiceServer).GetEntityWithPagination(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.EntityService/GetEntityWithPagination",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntityServiceServer).GetEntityWithPagination(ctx, req.(*EntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntityService_GetEntityWithStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EntityServiceServer).GetEntityWithStream(m, &entityServiceGetEntityWithStreamServer{stream})
}

type EntityService_GetEntityWithStreamServer interface {
	Send(*Entity) error
	grpc.ServerStream
}

type entityServiceGetEntityWithStreamServer struct {
	grpc.ServerStream
}

func (x *entityServiceGetEntityWithStreamServer) Send(m *Entity) error {
	return x.ServerStream.SendMsg(m)
}

// EntityService_ServiceDesc is the grpc.ServiceDesc for EntityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EntityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "main.EntityService",
	HandlerType: (*EntityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEntityWithPagination",
			Handler:    _EntityService_GetEntityWithPagination_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetEntityWithStream",
			Handler:       _EntityService_GetEntityWithStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "entity.proto",
}
